### ISSUE TITLE
未优化的 APK

### ISSUE THREAD

**Issue by ruanguihua** [fireantzhang/AppBundleDemo#1]
未优化的 APK
警告：

此 APK 会导致向用户发送用不到的代码和资源。如果使用 Android App Bundle，您的应用大小可以得到缩减。由于您的应用不会根据设备设置进行优化，所以用户必须在设备上下载和安装一些不必要的应用数据，应用就会较大。应用越大，安装成功率就越低，并且会在用户的设备上占用更多存储空间。

。。。。。。。。。。这样的意思是不是就用 App bundle 文件就好了

**Comment by fireantzhang** [comment]
@ruanguihua  对的，采用 App Bundle 格式发布更新之后就不会继续有这个警告了。

公司还有其他项目没用这个格式，每次更新都会有这个警告。

PS：另外更新一下情况，[fir-cli](https://github.com/FIRHQ/fir-cli) 目前已经支持上传 aab 格式的安装包【后续越来越多人用这个格式之后，他们会继续花精力优化相关体验的】
![image](https://user-images.githubusercontent.com/5302051/71507966-34ed7d80-28c1-11ea-8386-789126f0e495.png)
